Ten = ' *'
print (5 * Ten)
print (5 * Ten)
print (5 * Ten)
print ('')
print (5 * Ten)
print (Ten + ('  ' * 3) + Ten)
print (5 * Ten)
print ('')
print (' ' + Ten * 2 + ' ')
print (Ten + ' '*3 + Ten)
print (Ten + ' '*3 + Ten)
print (Ten + ' '*3 + Ten)
print (' ' + Ten * 2 + ' ')
print ('')
print (5 * Ten)
print ('  ' + Ten * 3 + ' ')
print ('  ' + Ten * 3 + ' ')
print ('  ' + Ten * 3 + ' ')
print (5 * Ten)